import json
from pathlib import Path
from typing import Callable

from .file.collector import collect_files
from .file.scanner import scan_files
from .file.selector import select_files, review_dangerous_files
from .file.media import classify_media_file, media_summary
from .file.textutil import relative_key as _rel_key
from .extract.code.extractor import extract_signatures, extract_dependencies, extract_api
from .extract.code.compressor import compress_file
from .text_references import find_text_references_for_file
from .tokenizer import analyze_tokens_with_payload
from .llm import analyze_rules, analyze_prompt, LANGUAGE_NAMES
from .freshness import build_manifest, load_previous_summaries
from .confidence import estimate_confidence, REVIEW_THRESHOLD
from .config import collection_kwargs
from .tech_stack import detect_tech_stack
from . import checkpoint as ckpt
from . import summarizer
from . import folder_summary

RESULT_DIR = Path(__file__).parent.parent.parent / "result"

# The AI-guide text a structural-only pack (use_llm=False) ships in place of
# an actual analyze_prompt() result -- so a reader (human or agent) sees why
# `project.prompt` reads like this instead of assuming the pack half-failed.
# One entry per supported packed-content language (llm.LANGUAGE_NAMES) --
# this is Ziplex's own fixed text, never an LLM call, so it follows the
# chosen `lang` the same way summarizer.py's structural-summary labels and
# SUMMARY_FAILED_PLACEHOLDERS do, rather than always shipping in English
# regardless of what language the rest of a Korean-language pack is in.
STRUCTURAL_ONLY_NOTE: dict[str, str] = {
    "en": (
        "This is a structural-only pack (--no-llm): no AI guide or coding-rule "
        "inference was run, and each file's summary is a deterministic listing "
        "of its own extracted signatures/dependencies, not an LLM-written "
        "description of what the file does."
    ),
    "ko": (
        "이 pack은 구조 정보 전용(--no-llm)입니다: AI 가이드나 코딩 룰 추론은 "
        "실행되지 않았고, 각 파일의 summary는 LLM이 작성한 설명이 아니라 추출된 "
        "시그니처/의존성을 그대로 나열한 결정적(deterministic) 결과입니다."
    ),
}

# A fixed (not LLM-generated) legend attached to every pack -- unlike
# STRUCTURAL_ONLY_NOTE above (explains one specific mode), this always ships,
# since aif.json is meant to survive outside any one tool session: committed
# to a repo, handed to a colleague, pasted cold into a web chat with none of
# Ziplex's own docs (this AGENTS.md, the MCP tool descriptions, the GUI's
# color-coded confidence badges) loaded alongside it. Without this, a reader
# in that position has no way to know what "confidence" means, what
# threshold is worth worrying about, or what the compressed body's own
# "⋮----" marker stands for -- all context that's otherwise only ever
# conveyed out-of-band. project.tech_stack/project.security_scan (see the
# aif assembly step below) are the same idea applied to *facts about this
# particular pack*; this is the one piece that's identical across every pack
# Ziplex has ever produced for a given language, so each language's version
# lives as one shared string instead of being computed per run -- same
# per-language dict shape as STRUCTURAL_ONLY_NOTE above, and for the same
# consistency reason.
FORMAT_NOTES: dict[str, str] = {
    "en": (
        "This file (and its sibling <name>.detail.json) was generated by Ziplex "
        "(https://github.com/taerim0/Ziplex) and human-reviewed before shipping "
        "-- edit it via `ziplex pack`'s correction step or the GUI review "
        "screen, not by hand. Each file's `confidence` (0.0-1.0) is a "
        f"heuristic: a score below {REVIEW_THRESHOLD} means the summary's "
        "wording didn't overlap much with the file's own extracted signatures, "
        "worth double-checking before trusting it. detail.json's compressed "
        "body uses '⋮----' to mark a function body Ziplex elided to save "
        "tokens -- everything else (signatures, imports, decorators) is left "
        "untouched."
    ),
    "ko": (
        "이 파일(및 형제 파일 <name>.detail.json)은 Ziplex "
        "(https://github.com/taerim0/Ziplex)가 생성하고 사람이 검토한 뒤 만든 "
        "결과입니다 -- 직접 수정하지 말고 `ziplex pack`의 보정 단계나 GUI 리뷰 "
        f"화면을 통해 수정하세요. 각 파일의 `confidence`(0.0-1.0)는 휴리스틱 "
        f"점수입니다: {REVIEW_THRESHOLD} 미만이면 summary의 표현이 그 파일의 "
        "실제 시그니처와 많이 겹치지 않았다는 뜻이니 신뢰하기 전에 다시 확인하는 "
        "것이 좋습니다. detail.json의 compressed 본문에서 '⋮----'는 Ziplex가 "
        "토큰 절감을 위해 생략한 함수 본문을 표시합니다 -- 그 외(시그니처, "
        "import, 데코레이터)는 그대로 남아 있습니다."
    ),
}


# Cap on how many per-file summaries feed analyze_prompt()'s own
# "architecture" context -- keeps a genuinely large project's prompt from
# growing unbounded (every other capped list in this codebase -- tech_stack's
# MAX_DEPENDENCIES, the relationship editor's REL_GRAPH_MAX_NEIGHBORS -- takes
# the same "enough real signal, not a full dump" stance). Ziplex's own stated
# audience (solo/personal-GitHub/small-team, see the roadmap's scope note)
# means most real projects stay well under this anyway.
MAX_ARCHITECTURE_FILES = 80


def _build_architecture_summary(files_data: dict, tech_stack: list[dict]) -> list[str]:
    """Real project-understanding signal for analyze_prompt() -- what it used
    to always receive as an empty list (a dead parameter, never actually
    populated anywhere), which is the confirmed root cause of a real,
    reported problem: an AI guide reading like a coding-style blurb rather
    than a "what is this project" summary, since project_name plus a list of
    naming-convention rules is *all* analyze_prompt() ever had to work with.

    Built from each file's own already-generated `summary` (this runs after
    the summary-generation step, so every file_data entry has one) plus the
    free tech_stack fact block -- both already paid for or free, no new LLM
    call needed to gather this. Capped at MAX_ARCHITECTURE_FILES, keeping
    dict insertion order (roughly collection order) rather than sorting,
    since this is prompt input, not a displayed list a human reads in order.
    """
    lines = []
    for stack in tech_stack:
        # tech_stack.detect_tech_stack()'s own shape -- one dict per
        # manifest found, not a flat list of dependency-name strings.
        deps = ", ".join(stack.get("dependencies", []))
        lines.append(f"Tech stack ({stack.get('language', '?')}, {stack.get('manifest', '?')}): {deps}")

    file_lines = [f"{name}: {data['summary']}" for name, data in files_data.items() if data.get("summary")]
    if len(file_lines) > MAX_ARCHITECTURE_FILES:
        remaining = len(file_lines) - MAX_ARCHITECTURE_FILES
        file_lines = file_lines[:MAX_ARCHITECTURE_FILES]
        file_lines.append(f"... ({remaining} more files not shown)")
    lines.extend(file_lines)
    return lines


def _confirm_regenerate_failed_summaries(failed_names: list[str], interactive: bool) -> bool:
    """Asks whether to drop the cached failure placeholder
    (summarizer.is_summary_failed_placeholder()/SUMMARY_FAILED_PLACEHOLDERS)
    for `failed_names` so this run retries them for real, instead of
    load_previous_summaries() silently carrying the same failure text
    forward pack after pack until the file's content itself happens to
    change.

    Same shape as checkpoint.resume_checkpoint_choice() -- a numbered
    menu, non-interactive callers get a safe default with no prompt.
    Defaults to leaving them cached (not regenerating): a repeated LLM
    failure isn't retried automatically anywhere else in the pipeline
    either (see generate_summaries()'s own docstring -- review is what's
    supposed to catch it, not a silent retry loop), and confidence.py
    already forces these to 0.0 so a human reviewing the pack sees them
    flagged regardless of which way this defaults.
    """
    if not interactive:
        return False

    print(f"\n  ⚠️  이전 pack에서 요약 생성에 실패한 파일 {len(failed_names)}개가 캐시에 있습니다:")
    for name in failed_names:
        print(f"      - {name}")
    print("  [1] 다시 생성 시도")
    print("  [2] 그대로 둠 (검토 단계에서 확인)")
    choice = input("  선택: ").strip()
    return choice == "1"


def _maybe_stop(
    check_cancelled: Callable[[], str | None] | None,
    root_path: str, root: Path, files_data: dict, rules: list | None = None, prompt: str = "",
    lang: str = "en",
) -> bool:
    """True if `check_cancelled` says to stop -- checkpointing first
    (reusing checkpoint.build_snapshot(), the exact shape handle_llm_failure()
    already checkpoints, so a stopped-and-saved run auto-resumes next time
    exactly like a failed one does) unless it said "discard". False (never
    stops) when check_cancelled wasn't given at all -- the CLI's synchronous
    run has no external thread to ask it to stop from in the first place;
    only a caller that runs pack() on a background thread (the GUI -- see
    gui/pack_service.py's request_cancel()) needs this, since a real Python
    thread can't be safely killed from outside once started.

    lang is recorded into the checkpoint (build_snapshot()) so a later
    pack() resuming it can tell whether it was saved under the same
    language selection as the resuming run -- see pack()'s own
    `lang_matches` for why that comparison matters.
    """
    if check_cancelled is None:
        return False
    action = check_cancelled()
    if action is None:
        return False
    if action == "save":
        ckpt.save_checkpoint(root_path, ckpt.build_snapshot(root, files_data, rules, prompt, lang))
    return True


def pack(
    root_path: str,
    auto: bool = False,
    interactive: bool = True,
    use_cache: bool = True,
    use_llm: bool = True,
    preselected: list[str] | None = None,
    include: list[str] | None = None,
    ignore: list[str] | None = None,
    check_cancelled: Callable[[], str | None] | None = None,
    result_dir: str | Path | None = None,
    lang: str = "en",
    discard_checkpoint: bool | None = None,
) -> dict:
    """include/ignore are extra glob patterns (gitignore syntax -- see
    collect_files()'s own docstring for exactly how each is applied),
    unioned with whatever's already in the target project's .ziplex.json
    (config.py) rather than replacing it -- typically sourced from a CLI
    --include/--ignore flag for a one-off scope without editing the config
    file. Both apply before file selection (auto/preselected/interactive
    picker all choose from the same already-filtered candidate set), so a
    file excluded here never reaches the security scan or shows up as a
    choice at all, the same as one excluded by DEFAULT_IGNORE/.gitignore.

    auto controls file selection (skip the interactive picker, include all
    safe files); interactive controls whether a failing LLM call can prompt
    for input at all. The two are independent: `--auto` alone still lets
    checkpoint.handle_llm_failure() ask what to do on a repeated failure,
    while interactive=False makes that automatic (checkpoint + return {})
    even with file selection left interactive. `cli.py`'s `--auto-correct`
    sets both this and whether corrector.py's interactive review runs
    afterward, since both boil down to the same question: is there a
    terminal to prompt?

    preselected, when given, wins over both auto and the interactive
    select_files() picker: a list of relative names (the same keys aif.json
    ends up keyed by) to include, already decided by the caller. This is
    gui_server.py's seam -- pack_service.py's file-selection screen runs
    collect_files()/scan_files() itself to show a human the safe/dangerous
    split in the browser, then passes back what they checked, since
    select_files()'s input()-based picker has no terminal to read from over
    HTTP. An empty list is valid input (selects nothing, same as an empty
    picker response) and not the same as None (which falls through to
    auto/select_files()).

    use_cache controls incremental reuse (staleness stage 2): when a
    previous successful pack is found at the conventional RESULT_DIR path
    for this project (or result_dir, if given -- see this function's own
    note on that param, further down), any file whose content hash still
    matches gets its
    summary reused instead of spending another LLM call on it. Only summary
    is reused -- signatures/dependencies/api/compressed are always
    freshly extracted, so a human's prior manual reparenting
    (corrector.py's move_file()) never silently gets skipped along with an
    unchanged file's dependency data; a fresh pack always rebuilds
    `relationships` from scratch regardless of this flag, same as before
    incremental reuse existed. use_cache=False (CLI: `pack --no-cache`)
    also discards a leftover checkpoint from an interrupted previous run,
    not just previous summaries -- "ignore anything cached from before"
    means the checkpoint too; without this, a non-interactive caller (the
    GUI, always) would silently auto-resume that checkpoint regardless of
    use_cache, which read as a bug from the outside (a "완전히 재패킹"
    checkbox not actually starting fresh) even though each half worked as
    designed in isolation.

    discard_checkpoint overrides just that second half of use_cache's
    effect, independent of the first: `None` (every CLI call, and the GUI's
    own fresh "패킹 시작") keeps today's behavior (`not use_cache` decides
    it); an explicit `False` forces a leftover checkpoint to always be
    resumed regardless of what use_cache says. This exists specifically for
    the GUI's "다시 시도" (retry-after-failure) button, which reposts a
    failed job's own original settings verbatim -- including whatever
    use_cache value that job started with. Without this override, retrying
    a job that started with "완전히 재패킹" checked would discard the very
    checkpoint that same job had just saved seconds earlier on its own LLM
    failure, silently re-billing every file's summary from scratch on every
    retry -- a real bug reported directly, and a case use_cache was never
    meant to cover: "완전히 재패킹" is about distrusting an *old, unrelated*
    prior pack's cache, not about discarding a checkpoint this exact retry
    exists to resume.

    use_llm=False (CLI: `pack --no-llm`) skips every LLM call entirely --
    no GEMINI_API_KEY, no network, no Gemini rate limits -- for the
    "structural-only" mode floated as a mitigation for the biggest
    non-developer onboarding barrier (getting an API key at all; see the
    `ziplex-roadmap` memory's target-audience discussion). Everything
    Tree-sitter/regex-based already runs unaffected (extraction,
    compression, tech_stack detection, the dependency graph); only the
    three LLM-touching steps change: each file's `summary` comes from
    summarizer.generate_structural_summaries() instead (a deterministic
    listing of its own signatures/dependencies -- see that function's
    docstring for exactly why this isn't pretending to be a real
    description), `rules` stays `[]` (nothing to infer without an LLM
    reading signature patterns), and `prompt` becomes STRUCTURAL_ONLY_NOTE
    instead of an AI-written guide, so a reader sees *why* those fields
    look like this rather than assuming the pack half-failed. use_cache
    still applies independently -- a file whose previous *real* summary is
    still fresh gets that reused rather than downgraded to a structural
    placeholder, since reusing a better answer already on hand is strictly
    an improvement, not a contradiction of "don't call the LLM now." One
    exception: a reused summary that's exactly summarizer's failure
    placeholder never got a real answer in the first place, so it isn't
    "reuse" so much as re-caching a miss -- see
    _confirm_regenerate_failed_summaries() below.

    A recognized media asset (image/video/audio/font -- file/media.py's
    classify_media_file(), extension and content both confirmed) is
    unconditionally structural-only regardless of
    use_llm: it never reaches Tree-sitter extraction (nothing to parse) or
    an LLM call (describing what an image/video actually *shows* would need
    a vision-capable model, real per-file cost this pipeline deliberately
    doesn't pay -- see media.py's own docstring). Its `summary` is a free,
    deterministic metadata line (kind, size, and pixel dimensions for the
    image formats media.py knows how to header-parse) filled in during
    extraction itself, which is what keeps it out of the LLM/structural
    `pending` set below either way.

    check_cancelled, if given, is polled at a few natural checkpoints (once
    per file during extraction, once more right before the LLM summary
    step, and once right after it) and should return None to keep going, or
    "save"/"discard" to stop early -- see _maybe_stop()'s own docstring for
    exactly what each does. The third checkpoint exists specifically so a
    stop requested *during* the summary step (typically the longest-running
    one, and the one with no way to interrupt its own thread pool mid-
    flight) still takes effect the moment that step finishes, instead of
    sitting unconsumed for the rest of the run. Only meaningful for a caller running pack() on its own background
    thread with no other way to interrupt it (gui/pack_service.py's
    "running"-state stop buttons); a plain CLI run has no such caller and
    just leaves this unset, same as `interactive` prompts never firing for
    the GUI's own non-interactive `pack()` calls. Not instant either way --
    a network-bound LLM call already in flight when a stop is requested
    still completes before the next checkpoint is reached.

    result_dir overrides RESULT_DIR as where use_cache's incremental-reuse
    lookup (load_previous_summaries(), just below) looks for a previous
    successful pack -- not where *this* run's own aif.json ends up (that's
    always whatever save_aif() is called with separately, after pack()
    returns). Only meaningful together with a caller that also saves to a
    non-default folder: gui/pack_service.py's start_pack_job() resolves a
    project's effective output folder (settings.py's per-project pin, else
    its global default, else nothing configured) once, up front, and passes
    the exact same folder both here and to save_aif() later, so cache
    lookup and the actual save destination never drift apart. None (the
    CLI's only call shape) keeps today's behavior exactly: RESULT_DIR,
    unconditionally.

    lang picks which language every LLM-written value (each file's summary,
    `rules`, `prompt`) is actually written in -- llm.py's LANGUAGE_NAMES
    holds the supported set ("en"/"ko" as of this writing), "en" both the
    default and the recommended choice (see that dict's own comment for
    why). Also picks the language of Ziplex's own fixed strings that ship
    alongside them for consistency: STRUCTURAL_ONLY_NOTE/FORMAT_NOTES above
    and summarizer.SUMMARY_FAILED_PLACEHOLDERS. Silently normalized to "en"
    if not a recognized key (a stale GUI request, a hand-built API call)
    rather than raising -- the CLI's own `--lang` flag and the GUI's pack-
    form dropdown both already restrict input to LANGUAGE_NAMES's keys, so
    this is just a defensive fallback, not the primary validation. Recorded
    verbatim as `project.language` in the assembled aif (see the aif
    assembly step, further down) for the same transparency reason
    project.tech_stack/security_scan/format_notes are always attached --
    a reader with no other context should be able to tell what language a
    pack's own content is in without guessing from the text itself.
    """
    if lang not in LANGUAGE_NAMES:
        lang = "en"
    root = Path(root_path)
    # .resolve() specifically for the display/save name -- root itself stays
    # unresolved so _rel_key(fp, root) below stays consistent with
    # collector.py's own separately-unresolved root (both relative when
    # root_path is relative, both absolute when it's absolute). Path(".").name
    # is "" (no name component at all), so an unresolved root_path of "."
    # (packing a project from inside its own folder, a common real pattern)
    # used to silently save an empty project name -- result/.json, an aif.json
    # with project.name == "", etc.
    project_name = Path(root_path).resolve().name
    effective_result_dir = Path(result_dir) if result_dir else RESULT_DIR

    # auto-detect a checkpoint -- use_cache=False means "ignore anything
    # cached from before, pack this fully fresh," which includes a leftover
    # checkpoint from an interrupted run, not just previous summaries (see
    # this function's own use_cache docstring, further up). Short-circuits
    # before ever calling resume_checkpoint_choice() in that case, so a
    # non-cached run never gets an interactive resume-or-discard prompt (or
    # a silent auto-resume, non-interactively) for something the caller
    # already said to ignore. discard_checkpoint (see this function's own
    # docstring) lets a caller override just this half of use_cache's
    # effect -- the GUI's retry-after-failure flow forces False here so
    # retrying a job that started with "완전히 재패킹" checked doesn't
    # discard the checkpoint that same job just saved on its own failure.
    should_discard_checkpoint = (not use_cache) if discard_checkpoint is None else discard_checkpoint
    checkpoint = ckpt.load_checkpoint(root_path)
    # A forced resume (discard_checkpoint is False, only ever the GUI retry
    # flow) still has to actually be *this* job's own checkpoint before it's
    # trusted -- checkpoints are keyed by project path only
    # (checkpoint._checkpoint_path()), never by which job produced them, so
    # two overlapping pack attempts for the same project (a second browser
    # tab, or a fresh "패킹 시작" left open while an earlier failed job's
    # error screen never got retried) could otherwise let this retry
    # silently resume a *different* attempt's partial progress instead of
    # its own -- a real gap caught by code review. A checkpoint whose own
    # restored file set isn't a subset of what this retry is actually about
    # to select clearly belongs to a different run; discard it unconditionally
    # in that case -- "does this checkpoint belong to me" and "should I trust
    # my own summary cache" (use_cache) are independent questions, so falling
    # back to `not use_cache` here (a second code-review pass caught this:
    # with use_cache=True, `not use_cache` is False, silently un-doing the
    # very mismatch this check just detected and resuming the foreign
    # checkpoint's rules/prompt anyway) is wrong regardless of use_cache.
    if checkpoint and discard_checkpoint is False and preselected is not None:
        _, _, candidate_files_data, _ = ckpt.unpack_snapshot(checkpoint)
        if not set(candidate_files_data.keys()) <= set(preselected):
            should_discard_checkpoint = True
    if checkpoint and (should_discard_checkpoint or not ckpt.resume_checkpoint_choice(interactive)):
        checkpoint = None
        ckpt.delete_checkpoint(root_path)

    # restore from checkpoint
    restored_rules, restored_prompt, restored_files_data, restored_lang = ckpt.unpack_snapshot(checkpoint)
    # True only when there's actually a checkpoint to compare against -- a
    # fresh run (no checkpoint) has nothing stale to discard, so restored_*
    # (already the ""/[]/{} defaults from unpack_snapshot(None)) are used
    # as-is regardless of this flag. When a checkpoint *does* exist but was
    # saved under a different `lang` (a forgotten --lang flag, a changed
    # selection on resume), its rules/prompt/per-file summaries are written
    # in a stale language -- reusing them verbatim would ship an aif.json
    # whose `project.language` claims one language while some content is
    # actually in another, the same self-contradiction class this codebase
    # already fixed once for rules/prompt vs. `use_llm` (see below).
    lang_matches = restored_lang == lang
    if checkpoint and not lang_matches:
        print(f"  ⚠️  체크포인트가 다른 언어({restored_lang})로 생성됨 -- rules/AI 가이드/요약을 {lang}(으)로 다시 생성합니다")

    # 1. Collect files
    print("\n📁 파일 수집 중...")
    files = collect_files(root_path, **collection_kwargs(root_path, extra_include=include, extra_ignore=ignore))

    # 2. Security scan
    print("🔒 보안 스캔 중...")
    scan_result = scan_files(files)
    safe_files = scan_result["safe"]
    dangerous = scan_result["dangerous"]
    included_anyway = []

    if dangerous:
        # Only ever asked when interactive (--auto-correct's *absence*) --
        # the same gate as every other "can we ask the terminal something"
        # decision already in this pipeline (checkpoint resume,
        # handle_llm_failure, the regenerate-cached-summary confirm),
        # independent of `auto` -- auto only changes *how* the already-safe
        # set gets selected below, not whether a human can still be asked
        # about a security decision. Non-interactive callers (--auto-correct)
        # keep today's behavior: excluded, no prompt, no way back short of
        # a second interactive run.
        included_anyway = review_dangerous_files(dangerous, root_path) if interactive else []
        if included_anyway:
            safe_files = safe_files + included_anyway

    # 3. Select files
    if preselected is not None:
        # Trusts a name from `dangerous` too, not just safe_files: naming
        # one here already *is* the caller's explicit decision -- the GUI's
        # file-selection screen shows the same reason/matched-line detail
        # review_dangerous_files() prints above, just as a checkbox a human
        # ticks before ever calling start_pack_job(), not a prompt pack()
        # itself raises. A scripted/CI caller that builds `preselected`
        # without a human in the loop simply never names a dangerous file's
        # key in the first place.
        #
        # Excludes anything already folded into safe_files via
        # included_anyway above -- interactive=True plus a preselected list
        # both naming the same dangerous file isn't a real call site today
        # (the GUI always passes interactive=False), but without this a
        # file approved both ways would appear twice in `candidates` and
        # get selected (and summarized) twice.
        wanted = set(preselected)
        candidates = safe_files + [d["file"] for d in dangerous if d["file"] not in included_anyway]
        selected = [f for f in candidates if _rel_key(f, root) in wanted]
        print(f"  ✅ {len(selected)}개 파일 선택됨 (지정된 목록 기준)")
    elif auto:
        selected = safe_files
        print(f"  ✅ 전체 {len(selected)}개 파일 선택됨")
    else:
        selected = select_files(safe_files, root_path)

    # Logged against the *actual* final outcome (dangerous file not in
    # `selected`), not `included_anyway` -- a real bug reported directly:
    # `included_anyway` only ever gets populated by the interactive
    # CLI-prompt path (review_dangerous_files(), just above), so for a
    # preselected (GUI) caller it stays [] regardless of what was actually
    # checked, and the old version of this log printed every dangerous
    # file as "excluded" unconditionally right after the scan -- before
    # `preselected` ever got a chance to include one of them. The pack
    # itself was never wrong (a checked "include anyway" box really did
    # end up in `selected`), just this log message, confusingly claiming
    # the opposite of what was about to happen. `security_scan` (the aif
    # assembly step, further down) already computes its own counts from
    # `selected` for the identical reason -- this log now matches it.
    if dangerous:
        selected_set = set(selected)
        excluded = [d["file"] for d in dangerous if d["file"] not in selected_set]
        if excluded:
            print(f"  ⚠️  민감 파일 제외: {len(excluded)}개")
            for f in excluded:
                print(f"  ❌ {Path(f).name}")

    if not selected:
        print("선택된 파일 없음.")
        return {}

    # incremental reuse (staleness stage 2): {relative key: summary} for
    # files whose content hasn't changed since the last successful pack
    previous_summaries = load_previous_summaries(root_path, selected, effective_result_dir, lang=lang) if use_cache else {}
    if previous_summaries:
        print(f"  ♻️  이전 pack에서 변경 없는 파일 {len(previous_summaries)}개 발견 — 요약 재사용")

        failed_previously = [
            name for name, summary in previous_summaries.items()
            if summarizer.is_summary_failed_placeholder(summary)
        ]
        if failed_previously and _confirm_regenerate_failed_summaries(failed_previously, interactive):
            for name in failed_previously:
                del previous_summaries[name]

    # 4. Tree-sitter analysis
    print("\n🔍 코드 구조 분석 중...")
    files_data = {}
    signatures_map = {}

    # All selected files' relative keys, computed once -- text_references.
    # find_text_references_for_file() needs the real candidate list to
    # match a non-code file's content against, not just file_path itself.
    all_names = [_rel_key(fp, root) for fp in selected]

    # Text-reference matches (see text_references.py), kept separate from
    # files_data[fp]["dependencies"] until *after* step 5's LLM summary
    # loop below, not merged in here -- summarizer.request_summary()/
    # analyze_batch_summaries() both switch a file's summary prompt from
    # content-based to signature/dependency-based the moment `dependencies`
    # is non-empty. Merging immediately would silently swap a text file's
    # (README, .tscn, ...) content-based prompt for a signatures=[]/
    # dependencies=[the very refs just found]-only one the instant it
    # picked up any text reference -- Gemini would summarize it having
    # never seen its actual content. Computed for every file regardless of
    # checkpoint-restore, so a run resumed mid-way still gets it.
    text_refs_by_path: dict[str, list[str]] = {}

    for file_path in selected:
        if _maybe_stop(check_cancelled, root_path, root, files_data, restored_rules, restored_prompt, lang):
            return {}

        name = _rel_key(file_path, root)
        # classify_media_file() computed once here and reused below (the
        # media-branch check further down) rather than called twice --
        # extension *and* content confirmed (see media.py's own docstring
        # for why extension alone isn't enough), which means it costs a
        # read_text() attempt for anything with a media extension. A
        # confirmed media file has no text content to scan for references
        # in the first place, so find_text_references_for_file() (which
        # would otherwise pay its own separate, redundant read_text()
        # attempt only to find nothing) is skipped for it outright.
        media_kind = classify_media_file(file_path)
        text_refs_by_path[file_path] = (
            [] if media_kind else find_text_references_for_file(file_path, name, all_names)
        )

        # restore from checkpoint
        if name in restored_files_data:
            print(f"  ✅ {name} (체크포인트에서 복원)")
            files_data[file_path] = dict(restored_files_data[name])
            if not lang_matches and files_data[file_path].get("summary"):
                # A summary already captured in a stale-language checkpoint
                # is exactly as wrong here as one reused across a language
                # change via load_previous_summaries() (freshness.py) would
                # be -- discard it so it falls into `pending` below and gets
                # regenerated in the currently requested `lang`.
                # signatures/dependencies/api/compressed aren't language-
                # dependent, so those are kept as-is.
                files_data[file_path]["summary"] = ""
            # Same condition the fresh-extraction branch below uses (`sigs
            # or deps`, not just `sigs`) -- this used to check "signatures"
            # alone, silently excluding a checkpoint-restored file that has
            # dependencies but no functions (e.g. a thin index.ts that's
            # just top-level imports) from analyze_rules()'s input. That
            # made the inferred coding rules depend on whether a run
            # happened to get interrupted and resumed, for an otherwise
            # identical pack.
            if files_data[file_path].get("signatures") or files_data[file_path].get("dependencies"):
                signatures_map[file_path] = files_data[file_path].get("signatures", [])
            continue

        # Media assets (images/video/audio/fonts, see file/media.py) never
        # reach Tree-sitter extraction or an LLM call at all -- there's no
        # code to parse and, deliberately, no vision-model call to make (see
        # media.py's own docstring for why that's out of scope). `summary`
        # is filled in right here with a free, deterministic metadata
        # description, which is what keeps it out of `pending` below (only
        # entries with no summary yet get one generated) -- this is the
        # actual mechanism that makes a media file cost nothing to pack.
        # media_kind was already computed above, before the checkpoint-
        # restore check -- reused here rather than calling
        # classify_media_file() a second time.
        if media_kind:
            reused_summary = previous_summaries.get(name, "")
            files_data[file_path] = {
                "signatures": [],
                "dependencies": [],
                "api": [],
                "compressed": "",
                "summary": reused_summary or media_summary(file_path, media_kind),
            }
            if reused_summary:
                print(f"  ♻️  {name} (변경 없음, 이전 요약 재사용)")
            else:
                print(f"  🖼️  {name} (미디어 파일, LLM 미사용)")
            continue

        sigs = extract_signatures(file_path)
        deps = extract_dependencies(file_path)
        apis = extract_api(file_path)
        compressed = compress_file(file_path)
        reused_summary = previous_summaries.get(name, "")

        files_data[file_path] = {
            "signatures": sigs,
            "dependencies": deps,
            "api": apis,
            "compressed": compressed,
            "summary": reused_summary
        }

        if sigs or deps:
            signatures_map[file_path] = sigs

        if reused_summary:
            print(f"  ♻️  {name} (변경 없음, 이전 요약 재사용)")
        else:
            print(f"  ✅ {name}")

    if _maybe_stop(check_cancelled, root_path, root, files_data, restored_rules, restored_prompt, lang):
        return {}

    # 5. Summary generation -- LLM-based (the default) or, with use_llm=False,
    # a deterministic structural fallback that never touches the network at
    # all (see this function's own docstring for the full use_llm story).
    # Each LLM-generated summary is human-reviewed/corrected in
    # correct_aif() later (triaged by confidence -- see below -- so review
    # effort scales with how many summaries actually look suspicious, not
    # with project size), so this skips the retry menu: try each file once
    # in parallel (see summarizer.generate_summaries) and fill failures with
    # a placeholder (a wrong summary still gets fixed in the next step).
    pending = {
        fp: data for fp, data in files_data.items() if not data.get("summary")
    }
    if use_llm:
        print("\n🤖 LLM 분석 중...")
        for fp, summary in summarizer.generate_summaries(pending, root, lang=lang).items():
            files_data[fp]["summary"] = summary
    else:
        print("\n📐 구조 정보만으로 요약 생성 중 (--no-llm, LLM 미사용)...")
        for fp, summary in summarizer.generate_structural_summaries(pending, root, lang=lang).items():
            files_data[fp]["summary"] = summary

    # Only now -- after every summary prompt has already been built from
    # code-only `dependencies` above -- fold in the free text-reference
    # matches computed earlier. `relationships` (built later, from this
    # same `dependencies` field) is meant to include them; the LLM summary
    # step just needed to not see them yet. See text_refs_by_path's own
    # comment above for why the ordering matters.
    for fp, data in files_data.items():
        if text_refs_by_path.get(fp):
            data["dependencies"] = data["dependencies"] + text_refs_by_path[fp]
            # Recorded separately (a subset of `dependencies`, exact
            # collected file names only) so build_tree() can tell a
            # text-reference-derived edge apart from a real Tree-sitter-
            # resolved import once both reach `relationships` -- closes the
            # limitation text_references.py's own docstring documents.
            # Assigned, not appended: this loop can re-run its merge against
            # an already-merged `dependencies` restored from a checkpoint
            # saved past this same step (see text_refs_by_path's comment
            # above), and a plain reassignment stays correct either way,
            # unlike appending twice into `dependencies` itself -- a
            # pre-existing, harmless duplicate build_tree() already dedupes.
            data["text_dependencies"] = list(text_refs_by_path[fp])

    # Confidence signal for every summary (reused, checkpoint-restored, or
    # freshly generated) -- free, no LLM call: just how much of the file's
    # own signature vocabulary shows up in its summary. correct_aif() uses
    # this to decide which summaries are worth prompting a human about.
    for data in files_data.values():
        data["confidence"] = estimate_confidence(data["summary"], data["signatures"])

    # A cancel requested *during* the summary step above (typically the
    # longest-running one) only gets checked once that step actually
    # finishes -- there's no way to interrupt generate_summaries()'s own
    # thread pool mid-flight from here. Without this checkpoint, a request
    # landing there would sit in job["cancel_action"] unconsumed until
    # pack() finishes on its own (reviewing state), never actually taking
    # effect.
    if _maybe_stop(check_cancelled, root_path, root, files_data, restored_rules, restored_prompt, lang):
        return {}

    # Computed once here (not just at final assembly, where this used to be
    # the only place it ran) so analyze_prompt() below can use it as real
    # architecture context too -- reused, not recomputed, at assembly time.
    tech_stack = detect_tech_stack(root_path)

    # A relative-keyed view of files_data for the two consumers below
    # (_build_architecture_summary()/folder_summary's functions) -- files_data
    # itself is still keyed by absolute path at this point in the pipeline
    # (final assembly's own _rel_key() conversion happens later, in step 7),
    # and an LLM prompt (or a shipped aif.json field) should never leak a
    # local absolute filesystem path.
    rel_files_data = {_rel_key(fp, root): data for fp, data in files_data.items()}

    # extract rules (restored from checkpoint if available)
    # use_llm=False ignores restored_rules outright, even if a checkpoint
    # left over from an earlier use_llm=True run has real inferred rules --
    # pack(use_llm=False)'s documented contract is that rules always ends
    # up [] (and prompt always ends up STRUCTURAL_ONLY_NOTE, see below).
    # Restoring a genuine prior LLM result here would silently ship an
    # aif.json with real coding rules alongside a prompt asserting no LLM
    # inference ever happened -- a direct self-contradiction in the same
    # document. lang_matches is the same guard for the same reason: a
    # checkpoint saved under a different `lang` has rules written in that
    # stale language, which would contradict the `project.language` this
    # run is about to claim.
    rules = restored_rules if (use_llm and lang_matches) else []
    if not rules and use_llm:
        print("  📋 코딩 룰 추출 중...")
        while not rules:
            rules_response = analyze_rules(signatures_map, lang=lang)
            try:
                rules_data = json.loads(rules_response)
                rules = rules_data.get("rules", [])
            except json.JSONDecodeError:
                rules = []

            if not rules:
                result = ckpt.handle_llm_failure(
                    "rules", "코딩 룰",
                    ckpt.build_snapshot(root, files_data, lang=lang),
                    root_path,
                    interactive=interactive,
                )
                if result == "EXIT":
                    return {}
                elif result is None:
                    continue
                else:
                    # Filtered, not just stripped: "".split(",") is ['']
                    # (a one-element list holding an empty string, not an
                    # empty list) -- pressing Enter with no input at this
                    # prompt used to silently become a single bogus
                    # empty-string rule instead of re-prompting, since
                    # `while not rules:` only re-loops on a genuinely
                    # empty list.
                    rules = [r.strip() for r in result.split(",") if r.strip()]
    elif rules:
        print("  📋 코딩 룰 (체크포인트에서 복원)")
    else:
        print("  📋 코딩 룰 추출 건너뜀 (--no-llm)")

    # generate prompt (restored from checkpoint if available)
    # Same use_llm/lang_matches guard as rules above, and for the same reason.
    prompt = restored_prompt if (use_llm and lang_matches) else ""
    if not prompt and use_llm:
        print("  ✍️  AI 가이드 생성 중...")
        while not prompt:
            prompt_response = analyze_prompt(
                project_name=project_name,
                architecture=_build_architecture_summary(rel_files_data, tech_stack),
                rules=rules,
                lang=lang,
            )
            try:
                prompt_data = json.loads(prompt_response)
                prompt = prompt_data.get("prompt", "")
            except json.JSONDecodeError:
                prompt = ""

            if not prompt:
                result = ckpt.handle_llm_failure(
                    "prompt", "AI 가이드",
                    ckpt.build_snapshot(root, files_data, rules, lang=lang),
                    root_path,
                    interactive=interactive,
                )
                if result == "EXIT":
                    return {}
                elif result is None:
                    continue
                else:
                    prompt = result
    elif prompt:
        print("  ✍️  AI 가이드 (체크포인트에서 복원)")
    else:
        print("  ✍️  AI 가이드 생성 건너뜀 (--no-llm)")
        prompt = STRUCTURAL_ONLY_NOTE.get(lang, STRUCTURAL_ONLY_NOTE["en"])

    # Per-folder summaries -- see folder_summary.py's own module docstring
    # for why this is a single best-effort call (structural fallback per
    # folder on any failure), not wired into the checkpoint/resume system
    # rules/prompt/per-file summaries all get.
    print("  🗂️  폴더 요약 생성 중..." if use_llm else "  🗂️  폴더 요약 생성 중 (구조 정보 기반)...")
    folders = (
        folder_summary.generate_folder_summaries(rel_files_data, lang=lang)
        if use_llm
        else folder_summary.generate_structural_folder_summaries(rel_files_data, lang=lang)
    )

    # 6. Token counting
    # Compares raw project text against the actual per-file aif.json payload
    # (just the summary -- signatures/dependencies/api/compressed are either
    # working state pruned later in correct_aif(), or split out to a sibling
    # detail.json by save_aif() and not part of what's loaded by default).
    # files_data is fully populated with summaries by now, so this reflects
    # the real savings an AI gets from reading aif.json.
    print("\n📊 토큰 분석 중...")
    token_results, _ = analyze_tokens_with_payload(selected, files_data)

    # Security-scan transparency: how many files step 2's scan_files() flagged
    # (`dangerous`), and what actually happened to them by the time file
    # selection (step 3) settled -- included after a human/GUI override, or
    # left excluded. Computed from the final `selected` list rather than the
    # `included_anyway` variable above, since that variable only covers the
    # interactive-CLI-prompt path; a preselected (GUI) caller can also name a
    # dangerous file directly without ever touching included_anyway. Always
    # attached, {0, 0, 0} when nothing was ever flagged -- same "always
    # present, zero/empty when N/A" convention tech_stack already uses, so a
    # reader can tell "scanned, found nothing" apart from "was this even
    # scanned at all," the same distinction repomix's own toggle-based
    # security-check notice exists to make, but backed by real counts instead
    # of an on/off flag, since Ziplex's scan always runs.
    dangerous_names = {_rel_key(d["file"], root) for d in dangerous}
    selected_names = {_rel_key(fp, root) for fp in selected}
    security_included = len(dangerous_names & selected_names)
    security_scan = {
        "flagged": len(dangerous_names),
        "included_anyway": security_included,
        "excluded": len(dangerous_names) - security_included,
    }

    # 7. Assemble AIF.json
    aif = {
        "project": {
            "name": project_name,
            "prompt": prompt,
            # Free (no LLM call), manifest-based fact block -- see
            # tech_stack.py's own docstring for why this exists alongside
            # `rules` rather than folding into it. Computed once, earlier
            # above (analyze_prompt() also uses it as architecture context),
            # not recomputed here.
            "tech_stack": tech_stack,
            "security_scan": security_scan,
            "format_notes": FORMAT_NOTES.get(lang, FORMAT_NOTES["en"]),
            # What language every LLM-written value (summaries/rules/prompt)
            # -- and, for use_llm=False, STRUCTURAL_ONLY_NOTE/the structural
            # summaries themselves -- was actually written in. See pack()'s
            # own `lang` param docstring for why this is always attached.
            "language": lang,
        },
        "rules": rules,
        # {folder path: {"summary": "..."}}, one entry per folder that
        # directly contains at least one collected file -- see
        # folder_summary.py for how each summary is generated. Editable via
        # edits.set_folder_summary() the same way per-file summaries/rules/
        # prompt are (corrector.py's terminal flow, pack_service.py's GUI
        # review flow) -- but without confidence-based triage of its own,
        # since folder_summary.py has no per-folder confidence signal.
        "folders": {folder: {"summary": summary} for folder, summary in folders.items()},
        "tokens": {
            model: {
                "original": data["original"],
                "compressed": data["compressed"],
                "saved_pct": data["saved_pct"]
            }
            for model, data in token_results.items()
        },
        "files": {
            _rel_key(fp, root): {
                "summary": data["summary"],
                "confidence": data["confidence"],
                "signatures": data["signatures"],
                "dependencies": data["dependencies"],
                # Present only for a file text_references.py actually found
                # a match for (packager.py's earlier merge step never adds
                # the key otherwise) -- working state, same as
                # signatures/dependencies/api, pruned by finalize_aif() once
                # build_tree() has folded it into `relationships` as
                # internal_text_refs.
                **({"text_dependencies": data["text_dependencies"]} if "text_dependencies" in data else {}),
                "api": data["api"],
                "compressed": data["compressed"]
            }
            for fp, data in files_data.items()
        },
        # Working state, not part of the shipped aif.json: a {file: content
        # hash} snapshot of exactly what was packed, so a later
        # freshness.check_freshness() call can tell whether this output has
        # drifted from the files on disk without re-running any of the above.
        # save_aif() pulls this out into a sibling <name>.cache.json, the
        # same way it pulls `compressed` out into <name>.detail.json.
        "_manifest": build_manifest(selected, root_path),
    }

    # delete the checkpoint on success
    ckpt.delete_checkpoint(root_path)

    return aif


def resolve_output_path(aif: dict, output_path: str | None) -> Path:
    """The path save_aif() will write aif.json to -- result/<project name>
    .json if output_path isn't given, otherwise output_path itself --
    factored out (no directory-creation or write side effects here, unlike
    save_aif() itself) so a caller that needs to know the destination
    *before* calling save_aif() can compute it identically instead of
    keeping its own copy of this fallback that could silently drift from
    save_aif()'s. gui/pack_service.py's submit_review() is exactly that
    caller: it locks this same path (see _lock_for_path()'s own comment)
    against a concurrent edit before finalizing and saving to it.
    """
    if output_path is None:
        return RESULT_DIR / f"{aif['project']['name']}.json"
    return Path(output_path)


def save_aif(aif: dict, output_path: str | None = None) -> None:
    """Writes the AIF result to output_path, or to result/<project name>.json if
    output_path isn't given (see resolve_output_path()) — mirroring
    checkpoint.CHECKPOINT_DIR, anchored to the repo root rather than the
    caller's cwd, so `pack` writes to the same place regardless of where
    it's invoked from.

    Splits two things out of `aif` into sibling files, keyed the same way as
    `files`:
    - `compressed` -> "<name>.detail.json". aif.json (summary + relationships)
      is what an AI reads by default -- for a file with no compressed body to
      strip (README, config, lang files, ...) `compressed` is close to the raw
      original, so shipping it unconditionally on every file undoes the token
      savings for exactly the files that benefit least from it. mcp_server.py's
      get_detail tool is what actually fetches detail.json today, only for
      files an AI decides it needs.
    - `_manifest` -> "<name>.cache.json" (flat, not per-file). A {file: content
      hash} snapshot of what was packed, for freshness.check_freshness() to
      compare against later -- not part of aif.json itself, since it's
      packaging-internal bookkeeping an AI reading the project has no use for.
    """
    output_path = resolve_output_path(aif, output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    manifest = aif.get("_manifest")

    lean_files = {}
    detail = {}
    for name, data in aif["files"].items():
        lean_files[name] = {k: v for k, v in data.items() if k != "compressed"}
        detail[name] = {"compressed": data.get("compressed", "")}

    lean_aif = {k: v for k, v in aif.items() if k != "_manifest"}
    lean_aif["files"] = lean_files

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(lean_aif, f, ensure_ascii=False, indent=2)
    print(f"\n✅ AIF.json 저장됨: {output_path}")

    detail_path = output_path.with_name(f"{output_path.stem}.detail.json")
    with open(detail_path, "w", encoding="utf-8") as f:
        json.dump(detail, f, ensure_ascii=False, indent=2)
    print(f"📦 상세 정보(compressed) 저장됨: {detail_path}")

    if manifest is not None:
        cache_path = output_path.with_name(f"{output_path.stem}.cache.json")
        with open(cache_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, ensure_ascii=False, indent=2)
        print(f"🗂️  캐시(해시) 저장됨: {cache_path}")
